import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import { use } from 'react';
import { ModeToggle } from '@/components/ModeToggle';
import { ThemeProvider } from '@/components/theme-provider';
import UserProfile from '@/components/UserProfile';
import { auth } from '@/lib/auth';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = use(auth());
  console.log('🚀 ~ RootLayout ~ session:', session);

  return (
    // 하이드레이션 워닝으 붙여줘야 서버/브라우저의 다크모드 토글러 오류 안남
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-5 antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {' '}
          <nav className="flex items-center justify-between">
            <div>
              Navigator <Link href="/hello">hello</Link>|
              <Link href="/hi">HI</Link>|<Link href="/shop/123">123</Link>|
              <Link href="/shop/123/456">123456</Link>|
              <Link href="/intercept">1ntercept</Link>|
              <Link href="/photos">Photo</Link>|
              <Link href="/caches">Caches</Link>|
              {session?.user ? (
                <Link href="/api/auth/signout">
                  `${session.user.name} 님 로그인 중`
                </Link>
              ) : (
                <Link href="/sign">sign</Link>
              )}
              |
            </div>
            <div className="flex items-center">
              <ModeToggle />
              <UserProfile />
            </div>
          </nav>
          <div className="border p-3">{children}</div>
          <footer className="text-center">footer</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
