import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import { SessionProvider } from 'next-auth/react';
import { use } from 'react';
import { ModeToggle } from '@/components/ModeToggle';
import { ThemeProvider } from '@/components/theme-provider';
import UserProfile from '@/components/UserProfile';
import { Separator } from '@/components/ui/separator';
import { auth } from '@/lib/auth';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = use(auth());
  console.log('🚀 ~ RootLayout ~ session:', session);

  return (
    // 하이드레이션 워닝으 붙여줘야 서버/브라우저의 다크모드 토글러 오류 안남
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-5 antialiased`}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {' '}
            <nav className="flex items-center justify-between">
              <div className="m-1 flex h-5 [&>div]:bg-red-400">
                Navigator <Link href="/hello">hello</Link>
                <Separator orientation="vertical" />
                <Link href="/hi">HI</Link>|<Link href="/shop/123">123</Link>
                <Separator orientation="vertical" />
                <Link href="/shop/123/456">123456</Link>
                <Separator orientation="vertical" />
                <Link href="/intercept">1ntercept</Link>
                <Separator orientation="vertical" />
                <Link href="/photos">Photo</Link>
                <Separator orientation="vertical" />
                <Link href="/caches">Caches</Link>
                {session?.user ? (
                  <Link href="/api/auth/signout">
                    {`${session.user.name} 님 로그인 중`}
                  </Link>
                ) : (
                  <Link href="/sign">sign</Link>
                )}
                |
              </div>
              <div className="flex items-center">
                <ModeToggle />
                {session?.user && <UserProfile />}
              </div>
            </nav>
            <div className="border p-3">{children}</div>
            <footer className="text-center">footer</footer>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
