spring:
  application:
    name: demo

  servlet:
    multipart:
      location: src/main/resources/static/tmp # tmp 폴더 미리 만들어야함
      max-request-size: 10MB
      max-file-size: 900KB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hana8
    password: hana8db

  flyway:
    enabled: false
    baseline-on-migrate: true  # 기존 DB가 있을 때 필요
  jpa:
    show-sql: true
    defer-datasource-initialization: false # !!!

    hibernate:
      ddl-auto: update # 실행시, 테이블을 만들지, 만들고 끌때 내릴지 등을 설정한다.
      naming:
        physical-strategy: # field명 그대로 column명 (default: SpringPhysicalNamingStrategy (userId ⇒ user_id))
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          time_zone: Asia/Seoul
        order_inserts: true # 같은 테이블끼리 묶어서 batch 전송
        order_updates: true # batch 효율을 위해 order_inserts/order_updates 같이 써야 효과적!
        format_sql: true # 쿼리문 줄바꿈과 들여쓰기 출력 여부 (show-sql일 경우 true) 이걸 쿼리가 콘솔에 보
        use_sql_comments: true # 쿼리문이 어떤 클래스에서 실행됐는지 출력 여부 (개발환경에서만 true)

  sql:
    init:
      mode: never #!!! never, embedded(H2 DB 쓸 때 사용) 등 있음

  web:
    resources:
      add-mappings: false
# file upload간 upload 경로 설정
upload:
  path: src/main/resources/static/upload
  secure: src/main/upload/secure


# 저장할때마다 오토리로드
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
#      additional-paths: src/main/java

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger.html
  api-docs:
    enabled: true
    path: /hana8/api-docs
