# @ = 변수 설정시 사용
@api = http://localhost:3000/api
### book list

GET {{api}}/books

### add book + post 할 body는 해당 api 아래에 적어줘야함
POST {{api}}/books

{
    "title":"New book",
    "writer" : "bean"
}

### get a book
GET {{api}}/books/2

### patch name
PATCH {{api}}/books/1

{
    "writer" : "bean"
}

### delete a book
DELETE {{api}}/books/2